# tls:
#   certificates:
#     - certFile: /etc/cert/*.zekro.de/fullchain.cer
#       keyFile:  /etc/cert/*.zekro.de/*.zekro.de.key

http:
  routers:
    https-redirect:
      rule: 'HostRegexp(`{any:.*}`)'
      middlewares: ['https-redirect']
      service: 'noop'
      entryPoints: ['http']

    sub-redirect:
      rule: 'HostRegexp(`{.*}.demo.zekro.de`)'
      middlewares: ['sub-redirect']
      service: 'noop'
      entryPoints: ['https']
      tls: {}
      priority: 1

  
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: 'https'
        permanent: true

    sub-redirect:
      redirectRegex:
        regex: '.*'
        replacement: 'https://demo.zekro.de'


  services:
    noop:
      loadBalancer:
        servers:
          - url: ''